Repository hanyang-art-therapy/backend, pull requests merged in 2025-05, with the labels that each got.

#2 [SETTING] 초기 프로젝트 세팅
  hanyang-arttherapy/.gitattributes
  hanyang-arttherapy/.github/ISSUE_TEMPLATE.md
  hanyang-arttherapy/.github/PULL_REQUEST_TEMPLATE.md
  hanyang-arttherapy/.gitignore
  hanyang-arttherapy/HELP.md
  hanyang-arttherapy/build.gradle
  hanyang-arttherapy/gradlew
  hanyang-arttherapy/gradlew.bat
  hanyang-arttherapy/script/pre-commit
  hanyang-arttherapy/settings.gradle
  hanyang-arttherapy/src/main/java/com/hanyang/arttherapy/HanyangArttherapyApplication.java
  hanyang-arttherapy/src/main/java/com/hanyang/arttherapy/common/config/.gitkeep
  hanyang-arttherapy/src/main/java/com/hanyang/arttherapy/common/exception/.gitkeep
  hanyang-arttherapy/src/main/java/com/hanyang/arttherapy/common/util/.gitkeep
  hanyang-arttherapy/src/main/java/com/hanyang/arttherapy/controller/.gitkeep
  hanyang-arttherapy/src/main/java/com/hanyang/arttherapy/domain/.gitkeep
  hanyang-arttherapy/src/main/java/com/hanyang/arttherapy/repository/.gitkeep
  hanyang-arttherapy/src/main/java/com/hanyang/arttherapy/service/.gitkeep
  hanyang-arttherapy/src/test/java/com/hanyang/arttherapy/HanyangArttherapyApplicationTests.java
Labels: ⚙ Setting

#4 [RENAME] 루트 디렉토리 구조 변경
  .gitattributes
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  HELP.md
  build.gradle
  gradlew
  gradlew.bat
  script/pre-commit
  settings.gradle
  src/main/java/com/hanyang/arttherapy/HanyangArttherapyApplication.java
  src/main/java/com/hanyang/arttherapy/common/config/.gitkeep
  src/main/java/com/hanyang/arttherapy/common/exception/.gitkeep
  src/main/java/com/hanyang/arttherapy/common/util/.gitkeep
  src/main/java/com/hanyang/arttherapy/controller/.gitkeep
  src/main/java/com/hanyang/arttherapy/domain/.gitkeep
  src/main/java/com/hanyang/arttherapy/repository/.gitkeep
  src/main/java/com/hanyang/arttherapy/service/.gitkeep
  src/test/java/com/hanyang/arttherapy/HanyangArttherapyApplicationTests.java
Labels: ⚙ Setting

#6 [FEAT] 공통 예외 구현
  .gitignore
  src/main/java/com/hanyang/arttherapy/common/exception/.gitkeep
  src/main/java/com/hanyang/arttherapy/common/exception/CustomException.java
  src/main/java/com/hanyang/arttherapy/common/exception/GlobalExceptionHandler.java
  src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/CommonExceptionType.java
  src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/ExceptionType.java
  src/main/resources/application.yml
Labels: ✨ Feature

#12 [FEAT] 파일 업로드
  src/main/java/com/hanyang/arttherapy/HanyangArttherapyApplication.java
  src/main/java/com/hanyang/arttherapy/common/config/AppConfig.java
  src/main/java/com/hanyang/arttherapy/common/entity/BaseEntity.java
  src/main/java/com/hanyang/arttherapy/common/exception/GlobalExceptionHandler.java
  src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/FileSystemExceptionType.java
  src/main/java/com/hanyang/arttherapy/common/init/DirectoryInit.java
  src/main/java/com/hanyang/arttherapy/controller/FileController.java
  src/main/java/com/hanyang/arttherapy/domain/Files.java
  src/main/java/com/hanyang/arttherapy/domain/enums/FilesType.java
  src/main/java/com/hanyang/arttherapy/dto/response/FileResponseDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/FileResponseListDto.java
  src/main/java/com/hanyang/arttherapy/repository/FilesRepository.java
  src/main/java/com/hanyang/arttherapy/service/FileStorageService.java
  src/main/java/com/hanyang/arttherapy/service/FileStorageUtils.java
  src/main/java/com/hanyang/arttherapy/service/LocalFileStorageService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ✨ Feature

#13 [FEAT] 파일 삭제
  src/main/java/com/hanyang/arttherapy/controller/.gitkeep
  src/main/java/com/hanyang/arttherapy/controller/FileController.java
  src/main/java/com/hanyang/arttherapy/domain/.gitkeep
  src/main/java/com/hanyang/arttherapy/repository/.gitkeep
  src/main/java/com/hanyang/arttherapy/repository/FilesRepository.java
  src/main/java/com/hanyang/arttherapy/service/.gitkeep
  src/main/java/com/hanyang/arttherapy/service/FileScheduledService.java
  src/main/java/com/hanyang/arttherapy/service/FileStorageService.java
  src/main/java/com/hanyang/arttherapy/service/LocalFileStorageService.java
Labels: ✨ Feature

#15 [TEST] 파일 테스트 - 로컬
  src/test/java/com/hanyang/arttherapy/service/LocalFileStorageServiceTest.java
Labels: ✅ Test

#24 [FEAT] 작가 조회
  src/main/java/com/hanyang/arttherapy/controller/ArtistController.java
  src/main/java/com/hanyang/arttherapy/service/ArtistsService.java
Labels: ✨ Feature

#25 [FEAT] 작가 정보 수정
  src/main/java/com/hanyang/arttherapy/controller/ArtistController.java
  src/main/java/com/hanyang/arttherapy/service/ArtistsService.java
Labels: ✨ Feature

#26 [FEAT] 작가 삭제
  src/main/java/com/hanyang/arttherapy/controller/ArtistController.java
  src/main/java/com/hanyang/arttherapy/service/ArtistsService.java
Labels: ✨ Feature

#28 [TEST] 작가 기능 테스트
  src/main/java/com/hanyang/arttherapy/repository/ArtistsRepository.java
  src/main/java/com/hanyang/arttherapy/service/ArtistsService.java
  src/test/java/com/hanyang/arttherapy/service/ArtistsServiceTest.java
Labels: ✅ Test

#46 [FEAT] 작품 상세 & 댓글 조회
  gradlew
  gradlew.bat
  src/main/java/com/hanyang/arttherapy/controller/ArtsController.java
  src/main/java/com/hanyang/arttherapy/controller/ReviewController.java
  src/main/java/com/hanyang/arttherapy/domain/ArtArtistRel.java
  src/main/java/com/hanyang/arttherapy/domain/Artists.java
  src/main/java/com/hanyang/arttherapy/domain/Arts.java
  src/main/java/com/hanyang/arttherapy/domain/Galleries.java
  src/main/java/com/hanyang/arttherapy/domain/Review.java
  src/main/java/com/hanyang/arttherapy/domain/enums/ArtType.java
  src/main/java/com/hanyang/arttherapy/dto/response/ArtsDetailResponseDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/GallerySimpleDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ReviewResponseDto.java
  src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
  src/main/java/com/hanyang/arttherapy/repository/FilesRepository.java
  src/main/java/com/hanyang/arttherapy/repository/ReviewRepository.java
  src/main/java/com/hanyang/arttherapy/service/ArtsService.java
  src/main/java/com/hanyang/arttherapy/service/ReviewService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#49 [FEAT] 전시회 전체 기능 통합 및 예외 처리 적용
  src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/GalleryExceptionType.java
  src/main/java/com/hanyang/arttherapy/controller/GalleriesController.java
  src/main/java/com/hanyang/arttherapy/domain/Galleries.java
  src/main/java/com/hanyang/arttherapy/repository/GalleriesRepository.java
  src/main/java/com/hanyang/arttherapy/service/GalleriesService.java
Labels: ✨ Feature

#55 [FEAT] 파일 삭제 - S3
  src/main/java/com/hanyang/arttherapy/controller/ArtistController.java
  src/main/java/com/hanyang/arttherapy/controller/FileController.java
  src/main/java/com/hanyang/arttherapy/service/FileScheduledService.java
  src/main/java/com/hanyang/arttherapy/service/FileStorageService.java
  src/main/java/com/hanyang/arttherapy/service/LocalFileStorageService.java
  src/main/java/com/hanyang/arttherapy/service/S3FileStorageService.java
Labels: ✨ Feature

#60 [FEAT] 파일 URL 자동 조합 기능
  build.gradle
  src/main/java/com/hanyang/arttherapy/common/init/DirectoryInit.java
  src/main/java/com/hanyang/arttherapy/service/FileStorageService.java
  src/main/java/com/hanyang/arttherapy/service/LocalFileStorageService.java
  src/main/java/com/hanyang/arttherapy/service/S3FileStorageService.java
Labels: ✨ Feature

#61 [FEAT] 댓글 등록, 수정, 삭제 & 작품 전체 조회
  src/main/java/com/hanyang/arttherapy/controller/ArtsController.java
  src/main/java/com/hanyang/arttherapy/controller/ReviewController.java
  src/main/java/com/hanyang/arttherapy/domain/ArtArtistRel.java
  src/main/java/com/hanyang/arttherapy/domain/Artists.java
  src/main/java/com/hanyang/arttherapy/domain/Arts.java
  src/main/java/com/hanyang/arttherapy/domain/Files.java
  src/main/java/com/hanyang/arttherapy/domain/Galleries.java
  src/main/java/com/hanyang/arttherapy/domain/Review.java
  src/main/java/com/hanyang/arttherapy/domain/Reviews.java
  src/main/java/com/hanyang/arttherapy/dto/request/ReviewRequestDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ArtsDetailResponseDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ArtsListResponseDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ArtsResponseDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/GalleryResponseDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/GallerySimpleDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ReviewResponseDto.java
  src/main/java/com/hanyang/arttherapy/repository/ArtArtistRelRepository.java
  src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
  src/main/java/com/hanyang/arttherapy/repository/FilesRepository.java
  src/main/java/com/hanyang/arttherapy/repository/GalleriesRepository.java
  src/main/java/com/hanyang/arttherapy/repository/ReviewRepository.java
  src/main/java/com/hanyang/arttherapy/service/ArtsService.java
  src/main/java/com/hanyang/arttherapy/service/ReviewService.java
Labels: ✨ Feature

#66 [DEPLOY] Dockerfile 추가
  Dockerfile
  src/main/java/com/hanyang/arttherapy/domain/Galleries.java
  src/main/java/com/hanyang/arttherapy/domain/UsersHistory.java
  src/main/java/com/hanyang/arttherapy/service/ReviewService.java
  src/main/resources/application.yml
Labels: 🌏 Deploy

#67 [REFACTOR] 작품 조회 및 댓글 기능 API 수정
  src/main/java/com/hanyang/arttherapy/controller/ArtsController.java
  src/main/java/com/hanyang/arttherapy/controller/ReviewController.java
  src/main/java/com/hanyang/arttherapy/domain/Arts.java
  src/main/java/com/hanyang/arttherapy/domain/Galleries.java
  src/main/java/com/hanyang/arttherapy/dto/request/ReviewRequestDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ArtsListResponseDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ArtsResponseDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ReviewResponseDto.java
  src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
  src/main/java/com/hanyang/arttherapy/repository/ReviewRepository.java
  src/main/java/com/hanyang/arttherapy/service/ArtsService.java
  src/main/java/com/hanyang/arttherapy/service/GalleriesService.java
  src/main/java/com/hanyang/arttherapy/service/ReviewService.java
Labels: 🔨 Refactor

#71 [REFACTOR] 페이지네이션 수정 및 Repository 주석
  src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
  src/main/java/com/hanyang/arttherapy/repository/ReviewRepository.java
  src/main/java/com/hanyang/arttherapy/service/ArtsService.java
Labels: 🔨 Refactor

#75 [REFACTOR] 엔티티 및 서비스 로직 수정
  src/main/java/com/hanyang/arttherapy/controller/ArtsController.java
  src/main/java/com/hanyang/arttherapy/controller/ReviewController.java
  src/main/java/com/hanyang/arttherapy/domain/ArtArtistRel.java
  src/main/java/com/hanyang/arttherapy/domain/Arts.java
  src/main/java/com/hanyang/arttherapy/domain/Galleries.java
  src/main/java/com/hanyang/arttherapy/domain/Reviews.java
  src/main/java/com/hanyang/arttherapy/dto/request/GalleriesRequestDto.java
  src/main/java/com/hanyang/arttherapy/dto/request/ReviewRequestDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ArtsListResponseDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ArtsResponseDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ReviewResponseDto.java
  src/main/java/com/hanyang/arttherapy/repository/ArtArtistRelRepository.java
  src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
  src/main/java/com/hanyang/arttherapy/repository/GalleriesRepository.java
  src/main/java/com/hanyang/arttherapy/repository/ReviewRepository.java
  src/main/java/com/hanyang/arttherapy/service/ArtsService.java
  src/main/java/com/hanyang/arttherapy/service/GalleriesService.java
  src/main/java/com/hanyang/arttherapy/service/ReviewService.java
Labels: 🔨 Refactor

#77 [REFACTOR] galleriesNo 수정에 따른 서비스 및 컨트롤러 수정
  src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/ArtsExceptionType.java
  src/main/java/com/hanyang/arttherapy/controller/ArtsController.java
  src/main/java/com/hanyang/arttherapy/controller/ReviewController.java
  src/main/java/com/hanyang/arttherapy/domain/Galleries.java
  src/main/java/com/hanyang/arttherapy/dto/request/GalleriesRequestDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ArtsListResponseDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ArtsResponseDto.java
  src/main/java/com/hanyang/arttherapy/repository/ArtArtistRelRepository.java
  src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
  src/main/java/com/hanyang/arttherapy/repository/GalleriesRepository.java
  src/main/java/com/hanyang/arttherapy/repository/ReviewRepository.java
  src/main/java/com/hanyang/arttherapy/service/ArtsService.java
  src/main/java/com/hanyang/arttherapy/service/GalleriesService.java
  src/main/java/com/hanyang/arttherapy/service/ReviewService.java
Labels: 🔨 Refactor

#79 [REFACTOR] 하드코딩된 유저 ID 삭제 및 수정
  src/main/java/com/hanyang/arttherapy/service/ReviewService.java
Labels: 🔨 Refactor

#81 [DEPLOY] 배포를 위한 시큐리티 설정 추가
  src/main/java/com/hanyang/arttherapy/common/aws/config/AmazonConfig.java
  src/main/java/com/hanyang/arttherapy/common/config/SecurityConfig.java
  src/main/java/com/hanyang/arttherapy/controller/ArtistController.java
  src/main/java/com/hanyang/arttherapy/service/S3FileStorageService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 🌏 Deploy

#82 [DEPLOY] deploy/#80
  src/main/java/com/hanyang/arttherapy/controller/HealthCheckController.java
Labels: 🌏 Deploy

#86 [CHORE] 경로 누락 수정
  src/main/java/com/hanyang/arttherapy/controller/ArtistController.java
Labels: 🌏 Deploy

#88 [REFACTOR] 리뷰 CRUE 기능 개선 및 미로그인 사용자 댓글 등록 기능 추가
  src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/ReviewException.java
  src/main/java/com/hanyang/arttherapy/controller/ArtsController.java
  src/main/java/com/hanyang/arttherapy/controller/ReviewController.java
  src/main/java/com/hanyang/arttherapy/dto/request/GalleriesRequestDto.java
  src/main/java/com/hanyang/arttherapy/dto/request/ReviewRequestDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ArtsListResponseDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ReviewResponseDto.java
  src/main/java/com/hanyang/arttherapy/repository/ArtsRepository.java
  src/main/java/com/hanyang/arttherapy/service/ArtsService.java
  src/main/java/com/hanyang/arttherapy/service/ReviewService.java
Labels: 🔨 Refactor

#102 [REFACTOR] 작품 조회 기능에 description, coDescription 수정
  src/main/java/com/hanyang/arttherapy/common/config/SecurityConfig.java
  src/main/java/com/hanyang/arttherapy/domain/Arts.java
  src/main/java/com/hanyang/arttherapy/dto/response/ArtArtistRelResponseDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ArtsListResponseDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/ArtsResponseDto.java
  src/main/java/com/hanyang/arttherapy/repository/ArtArtistRelRepository.java
  src/main/java/com/hanyang/arttherapy/service/ArtsService.java
  src/main/resources/application.yml
Labels: 🔨 Refactor

#113 [FEAT] 검색 및 게시글 삭제, 수정 기능 추가
  src/main/java/com/hanyang/arttherapy/common/exception/GlobalExceptionHandler.java
  src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/NoticeException.java
  src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/UserException.java
  src/main/java/com/hanyang/arttherapy/controller/NoticesController.java
  src/main/java/com/hanyang/arttherapy/controller/ReviewController.java
  src/main/java/com/hanyang/arttherapy/domain/Notices.java
  src/main/java/com/hanyang/arttherapy/repository/GalleriesRepository.java
  src/main/java/com/hanyang/arttherapy/repository/NoticesRepository.java
  src/main/java/com/hanyang/arttherapy/service/ArtsService.java
  src/main/java/com/hanyang/arttherapy/service/NoticesService.java
  src/main/java/com/hanyang/arttherapy/service/ReviewService.java
Labels: ✨ Feature

#130 [FEAT] 회원 전체 및 상세조회, 이름 조회 및 수정
  src/main/java/com/hanyang/arttherapy/common/exception/exceptionType/UserException.java
  src/main/java/com/hanyang/arttherapy/controller/AdminUserController.java
  src/main/java/com/hanyang/arttherapy/domain/Users.java
  src/main/java/com/hanyang/arttherapy/dto/request/userRequest/UserRequestDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/userResponse/UserDetailDto.java
  src/main/java/com/hanyang/arttherapy/dto/response/userResponse/UserDto.java
  src/main/java/com/hanyang/arttherapy/repository/UserRepository.java
  src/main/java/com/hanyang/arttherapy/service/AdminUserService.java
Labels: ✨ Feature
